[project]
name = "grove"
version = "1.0.1"
dependencies = [
    "click~=8.1",
    "django~=5.0",
    "django-environ~=0.11",
    "django-extensions~=3.2",
    "django-htmx~=1.17",
    "django-safedelete~=1.3",
    "djangosaml2~=1.9",
    "django-umd-lib-style>=1.1.0",
    # By default, Plastron Utils is installed from Github.
    # To use a local version for development, uncomment the following
    # line and comment the plastron-utils line with the Github URL
    # "plastron-utils~=4.0",
    "plastron-utils@git+https://github.com/umd-lib/plastron.git@4.0.0#subdirectory=plastron-utils",
    "rdflib~=7.0",
    'urlobject~=2.4',
    "waitress~=3.0",
    "whitenoise~=6.6",
]

[project.optional-dependencies]
prod = [
    "psycopg2-binary~=2.9",
]
test = [
    "debugpy~=1.8",
    "freezegun~=1.5",
    "pipdeptree~=2.16",
    "pytest~=8.1",
    "pytest-cov~=4.1",
    "pytest-datadir~=1.5",
    "pytest-django~=4.8",
    "ruff~=0.3",
]

[project.scripts]
grove = "grove.server:run"

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "grove.settings"

[tool.coverage.run]
# these were generated by Django
omit = [
    "asgi.py",
    "manage.py",
    "wsgi.py",
]

[tool.ruff]
line-length = 120
exclude = [
  # Ignore auto-generated "migrations" directories
  "migrations"
]

[tool.ruff.format]
quote-style = "single"

[tool.ruff.lint]
# preview is required to enable many pycodestyle rules see
# https://docs.astral.sh/ruff/rules/
preview = true

# Enable pycodestyle errors and warnings
select = ["E", "W"]
