# Generated by Django 5.0.1 on 2024-02-01 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'verbose_name_plural': 'properties'},
        ),
        migrations.AlterModelOptions(
            name='vocabulary',
            options={'verbose_name_plural': 'vocabularies'},
        ),
        migrations.AddField(
            model_name='term',
            name='name',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
    ]
