# Generated by Django 5.0.1 on 2024-02-03 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabs', '0003_predicate_alter_property_term_alter_term_vocabulary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='value',
            field=models.CharField(max_length=1024),
        ),
    ]
