# Generated by Django 5.0.3 on 2024-03-09 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabs', '0004_alter_property_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='vocabulary',
            name='description',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AddField(
            model_name='vocabulary',
            name='label',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='vocabulary',
            name='preferred_prefix',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
