# Generated by Django 5.0.3 on 2024-03-13 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabs', '0005_vocabulary_description_vocabulary_label_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vocabulary',
            name='label',
            field=models.CharField(max_length=256),
        ),
    ]
