# Generated by Django 5.0.4 on 2024-05-06 16:00

import django.utils.timezone
import django_extensions.db.fields
import vocabs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vocabs", "0006_alter_vocabulary_label"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="term",
            options={"get_latest_by": "modified"},
        ),
        migrations.AddField(
            model_name="property",
            name="created",
            field=django_extensions.db.fields.CreationDateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="created",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="property",
            name="modified",
            field=django_extensions.db.fields.ModificationDateTimeField(
                auto_now=True, verbose_name="modified"
            ),
        ),
        migrations.AddField(
            model_name="term",
            name="created",
            field=django_extensions.db.fields.CreationDateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="created",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="term",
            name="modified",
            field=django_extensions.db.fields.ModificationDateTimeField(
                auto_now=True, verbose_name="modified"
            ),
        ),
        migrations.AddField(
            model_name="vocabulary",
            name="created",
            field=django_extensions.db.fields.CreationDateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="created",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="vocabulary",
            name="modified",
            field=django_extensions.db.fields.ModificationDateTimeField(
                auto_now=True, verbose_name="modified"
            ),
        ),
        migrations.AlterField(
            model_name="vocabulary",
            name="uri",
            field=models.CharField(
                max_length=256, validators=[vocabs.models.VocabularyURIValidator()]
            ),
        ),
    ]
