# Generated by Django 5.0.4 on 2024-05-21 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabs', '0009_vocabulary_published'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='term',
            options={},
        ),
        migrations.AddConstraint(
            model_name='term',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted__isnull', True)), fields=('vocabulary', 'name'), name='unique_term_vocabulary_name', violation_error_message='A term with this name already exists in this vocabulary'),
        ),
    ]
